#!/usr/bin/env python3
"""Export Swift golden tests for the SigLIP 2 tokenizer (Gemma SentencePiece).

Usage: python export_tokenizer.py --checkpoint checkpoint --repo-root ../..
"""

import argparse
from pathlib import Path

from transformers import AutoTokenizer

CONTEXT_LENGTH = 64

GOLDEN_TEXTS = [
    "a photo of a dog running on a beach",
    "a close-up of hands typing on a laptop",
    "an establishing shot of a city skyline at night",
    "A CAT",
    "shot of the bridge at sunset, golden hour",
    "person speaking at a whiteboard (interview)",
    "b-roll: harbor, boats, 4k",
    "café exterior with neon sign",
    "café exterior with neon sign",
    "the    quick   brown\tfox",
    "don't stop believin'",
    "搜索海港的镜头",
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default="checkpoint")
    ap.add_argument("--repo-root", default="../..")
    args = ap.parse_args()
    root = Path(args.repo_root).resolve()

    tokenizer = AutoTokenizer.from_pretrained(args.checkpoint)
    cases = []
    for text in GOLDEN_TEXTS:
        ids = tokenizer(
            [text], padding="max_length", truncation=True, max_length=CONTEXT_LENGTH
        ).input_ids[0]
        swift_text = text.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
        cases.append(f'        ("{swift_text}", {ids}),')

    goldens = (
        "// Generated by models/siglip2/export_tokenizer.py — do not edit.\n"
        "enum TextTokenizerGoldens {\n"
        "    static let cases: [(text: String, tokens: [Int32])] = [\n"
        + "\n".join(cases)
        + "\n    ]\n}\n"
    )
    out = root / "Tests/PalmierProTests/Search/TextTokenizerGoldens.swift"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(goldens)
    print(f"wrote {len(GOLDEN_TEXTS)} goldens -> {out}")


if __name__ == "__main__":
    main()
